services:
  strapi:
    build: .
    container_name: startime-strapi
    restart: always
    env_file: postgres.env
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi_restore
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
    ports:
      - "1340:1340"
    volumes:
      - strapi_public:/app/public/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: startime-postgres
    restart: always
    environment:
      - POSTGRES_DB=strapi_restore
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    volumes:
      - strapi_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  strapi_db:
  strapi_public:
